### PR TITLE
Update README.md link to Personality Insights Demo

### PR DESCRIPTION
**Pull request by luish**

### CODE REVIEW

**Comment by germanattanasio** [comment]
Hi @luish the link should be `personality-insights-livedemo.mybluemix.net`

**Comment by glennrfisher** [comment]
Looks like the "View Demo" link on the [IBM Watson Developer Cloud Personality Insights](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/personality-insights.html) page links to `https://watson-pi-demo.mybluemix.net/`.

@germanattanasio: Any particular reason you suggest using `personality-insights-livedemo.mybluemix.net` instead? Should that Developer Cloud page be updated?

**Comment by luish** [comment]
Well, I see that the repo [personality-insights-java](https://github.com/watson-developer-cloud/personality-insights-java) links to the page mentioned by @germanattanasio. But I would suppose that `watson-pi-demo.mybluemix.net` is the correct one as it's on the official documentation.

**Comment by germanattanasio** [comment]
The official documentation should be updated too. @bvonhag can you please update the link to the demo for personality insights?

Demos aren't supposed to have `watson` or acronyms like `pi`.

**Comment by luish** [comment]
Alright, I've just corrected this pull request. 
Thanks @germanattanasio :+1:

**Comment by glennrfisher** [comment]
Thanks for this fix, @luish!

**Pull request merged**
