### PR TITLE
Add user agent header

### PR DESCRIPTION
**Pull request by glennrfisher**
This pull request adds a user-agent header to all REST requests. This was partially completed in previous releases, but still needed to be implemented within the `rest-kit` architecture.

The user agent includes the following information:
`sdk-version/service-version executable/bundle (version; os)`

### CODE REVIEW

**Comment by germanattanasio** [comment]
@glennrfisher can you give me an example of the `user-agent`?

**Comment by glennrfisher** [comment]
@germanattanasio: Sure. I created an app called `MyTestApp` and used it to print out the user agent:

`watson-developer-cloud-ios-0.3.1/AlchemyVisionV1 MyTestApp/com.glennrfisher.MyTestApp (1; OS Version 9.3 (Build 13E230))`

This allows us to extract the following information:
- SDK Version: `watson-developer-cloud-ios-0.3.1`
- SDK Service: `AlchemyVisionV1`
- Executable Name: `MyTestApp`
- Executable Bundle ID: `com.glennrfisher.MyTestApp`
- Executable Version: `1`
- OS Version: `9.3 (Build 13E230)`

**Comment by vherrin** [comment]
Code reviewed and looks good

**Comment by germanattanasio** [comment]
We can't get the executable name, bundle id or version without asking the user. We will run into legal issues

**Comment by glennrfisher** [comment]
That's fine, I can take it out. Any reference to the legal issues? Just curious what the problem would be or whether you've run into it in the past.

**Comment by glennrfisher** [comment]
Does that mean it's okay to leave the OS version in? It would be helpful to know the distribution of OS versions among our users.

**Comment by germanattanasio** [comment]
I think OS Version doesn't expose the user data. The application name is sensitive information.

**Comment by germanattanasio** [comment]
@glennrfisher can we also use 
```
watson-apis-ios-sdk/0.3.1
```

For the name and version

**Comment by glennrfisher** [comment]
Happy to do whatever you prefer.

Out of curiosity, though, why `watson-apis`, instead of `watson-developer-cloud`? You had specified `watson-developer-cloud` in [this issue comment](https://github.com/watson-developer-cloud/ios-sdk/issues/201#issuecomment-207013907) before.

To clarify, here's what the updated user-agent string would look like:

`watson-apis-ios-sdk/0.3.1 AlchemyVisionV1 (OS Version 9.3 (Build 13E230))`

**Comment by glennrfisher** [comment]
@vherrin: Can you review the most recent 4 commits? Assuming @germanattanasio signs off on the example user-agent strings above, then this PR should be ready to be merged.

**Comment by vherrin** [comment]
updates are valid

**Pull request merged**
