### PR TITLE
Image handling

### PR DESCRIPTION
**Pull request by thomaspaulmann**
### Summary

Using NSURL invokes some trouble with Image Handling. If you choose a Photo from your Camera Roll you get an UIImage or a referencing URL to the Asset. The Initializer NSData(contentsOfURL: ...), which is used in the [API](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/AlchemyVisionV1/AlchemyVision.swift#L105), does not handle Asset URLs correctly. 
It seems to me, that NSData reduces a lot of pains for the developers. They can choose what they want to use: Loading from Assets and convert to NSData or transforming UIImage to an UIImagePNGRepresentation and so on.

An other way would be, to use UIImage instead of NSData and make the conversation in the AlchemyVision API.

### Other Information

I am looking forward to your Feedback.

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
Same as always -> #322 :-) The Build Server does not have Credentials for external Builds.

**Comment by glennrfisher** [comment]
Cool! Nice catch. Really appreciate the input.

**Comment by thomaspaulmann** [comment]
@glennrfisher Thanks for the quick Merge! I will extend this to other APIs that takes Images as Input, f.e. VisualRecognition. 

I'm not completely sure if NSData is the right way to do it or if it's better to use UIImage. NSData gives the developer more freedom, because she can build the serialisation. On the other hand UIImage is clearer and fits better to the API, because you want to analyze an Image. What do you think, @glennrfisher ? Any thoughts on that?

**Comment by glennrfisher** [comment]
I've been thinking about NSData versus UIImage. I really like your suggestion, because UIImage would bring a lot of clarity to the API and make it easier for developers to understand.

There are a few questions that I have, though, and will need to investigate:

- The [Visual Recognition](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/VisualRecognitionV3/VisualRecognition.swift#L321) service has some functions that accept either a single image or a zip file of images. How would we modify the API in these situations to accept UIImage? --> I assume we would create two separate methods: `classify(image:...)` and `classify(images:...)`.

- To convert a UIImage to NSData, I assume we would use either [`UIImageJPEGRepresentation(_:_)`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html#//apple_ref/c/func/UIImageJPEGRepresentation) or [`UIImagePNGRepresentation(_:_)`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html#//apple_ref/c/func/UIImagePNGRepresentation). Which function would we want to use? Does it matter? How compressed are the resulting images?

- Will developers ever want more control over the data sent to Watson? Using UIImage may require an existing file to be transcoded into a different format, with different levels of detail. Might this frustrate some developers who, as you mention, would want more control over the whole serialization?

We really appreciate your input @thomaspaulmann! You've made lots of great suggestions, fixes, and are prompting really good conversations that will improve the SDK. Thanks!

**Comment by thomaspaulmann** [comment]
@glennrfisher thanks for the feedback and you're points are great. Actually I've thought about them yesterday, because I wanted to port also the Visual Recognition service to the similar approach. BTW what is the difference between this service and the Alchemy Vision? Both API looks very similar to me.

Anyways... Here are some _answers_ to your points:

- I don't know the exact logic that happen for the ZIP file but as an App Developer (iOS), I would like to pass in an Array of `UIImage`. Correct me if I'm wrong, but most of the times I will not have an ZIP file on my iPhone that I want to upload to this kind of service. It makes sense for macOS applications, so I would go with your idea of multiple methods.

- The size does matter! That's actually a bug that I wanted to provide, sorry guys 😀 Extracted images can be no larger than 1 MB, otherwise you get an error called [content-exceeds-size-limit](https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/alchemyvision/detailed_info.shtml). I would suggest [`UIImageJPEGRepresentation( _ : _ )`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html#//apple_ref/c/func/UIImageJPEGRepresentation). You can define a compression factor and I would love to see some logic in the SDK that tries to find the best compression for the image size limit.

- Does it make sense to support both? A high-level method that handles an Array of `UIImage` or at least a single `UIImage` and another method that handles the `NSData`? Maybe that is an approach that fit to both types of developer.

Should we open an Issue for this? That will make it easier for others to contribute and we can track that better.

**Comment by glennrfisher** [comment]
Thanks, @thomaspaulmann! I opened #353 to help us track and discuss this idea.

The new v3 upgrade to Visual Recognition makes it very similar to Alchemy Vision. I believe that was one of the team's goals for their v3 release. The AlchemyVision service is [being deprecated](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/alchemyvision/) in favor of the Visual Recognition service.

**Pull request merged**
