### PR TITLE
[general-sdk] add support for Xcode 7.3

### PR DESCRIPTION
**Pull request by glennrfisher**
This PR fixes errors that would occur when building the Watson Developer Cloud iOS SDK with Xcode 7.3. In particular, it:

- Removes the libogg and libopus libraries, which were causing build failures.
- Modifies the Text to Speech implementation to use WAV instead of OPUS.
- Repairs the corrupt WAV header returned by the Text to Speech service.
- Updates dependencies to Xcode 7.3 and Swift 2.2 compatible releases.
- Disables Xcode code coverage that caused errors with Xcode 7.3.
- Updates the readme with information about using Xcode 7.3.

Please note that all binaries must be re-built for use with Xcode 7.3 and Swift 2.2. To do so, please run: `carthage update --platform iOS --no-use-binaries`

Related Issues: #210

### CODE REVIEW

**Comment by germanattanasio** [comment]
@glennrfisher how are you  repairing the wav header? are you reading all the file to calculate the audio length ?

**Comment by glennrfisher** [comment]
@germanattanasio Yes, basically. There are two fields that need to be updated: the RIFF chunk size and the data subchunk size. I wrote a function that traverses through the data to calculate these values and then update them in the wav header.

**Comment by glennrfisher** [comment]
All tests are passing locally. I'm going to go ahead and merge these fixes into master then issue a new release.

**Comment by glennrfisher** [comment]
@germanattanasio: Here's [the function](https://github.com/watson-developer-cloud/ios-sdk/blob/d05d7d97295b26fdda380e483892b53d93ac0640/WatsonDeveloperCloud/TextToSpeech/TextToSpeech.swift#L272) to repair the WAV header.

**Comment by vherrin** [comment]
We really need to have the service fix the header size issue.  In its current state, every platform has to implement a fix from a corrupt wav file.

**Comment by germanattanasio** [comment]
@vherrin you are right. The good thing about opus is that you don't have a file length at the beginning.
I'm going to open an issue to discuss the WAV vs OPUS choice

**Comment by vherrin** [comment]
@germanattanasio Thanks!  One other point is having native mobile formats supported in the service as well.  It would really be nice to have the built-in formats on mobile devices supported by the service!

**Pull request merged**
