### PR TITLE
Fixed failing HTTP request when synthesizing TextToSpeech

### LINKED ISSUE #193: Text to Speech fails with 'Code=400 No JSON object could be decoded'
Looking forward to trying out text-to-speech and speech-to-text for potential use in a new app, but ran into a problem with the QuickStart example.  It's the same issue described in this [developerWorks question: "Watson texttospeech Code=400 No JSON object could be decoded - no sound played by app"](https://developer.ibm.com/answers/questions/256894/watson-texttospeech-code400-no-json-object-could-b/).  

I have a theory it may be due to the `contentType: .JSON` in the `WatsonRequest` created in `TextToSpeech().synthesize(_:voice:completionHandler:)`, since no content (JSON or otherwise) is added to the http message body.

### PR DESCRIPTION
**Pull request by teddynewell**
### What's this PR do?

Fixes TextToSpeech synthesis so the QuickStart example code works.

- Fixes the failing HTTP request in `TextToSpeech().synthesize(_:voice:completionHandler)` by removing the unneeded JSON content-type header. Since no HTTP message is included in the request body, the content-type is superfluous.
  - _Note: An extraneous content-type probably shouldn't cause a 400 response when the request body is empty for a GET request._

~~- Updates AlamofireObjectMapper version for Carthage compatibility and to fix [Carthage build error due to deployment targets](https://github.com/tristanhimmelman/AlamofireObjectMapper/issues/63) without introducing any API changes.~~
  ~~- Uses `~>` for maximum compatibility in the dependency graph~~

### Relevant Issues
Resolves #193

### CODE REVIEW

**Comment by teddynewell** [comment]
I made this small PR against `master` so it can be deployed as a hotfix @glennrfisher.  I see there may be [legal issues](https://github.com/watson-developer-cloud/ios-sdk/pull/187/files#r55229618) about updating dependency releases, so let me know if I should drop the Cartfile changes.

**Comment by kasunk** [comment]
Hi @teddynewell,

I had the same issue you had, Even thought I added your fixes and rebuild again it work for doesn't me.

**Comment by glennrfisher** [comment]
You're very right! The problem is with the `contentType: .JSON` line. I believe the Text to Speech service was updated to be stricter about requests.

I did [commit a fix](https://github.com/watson-developer-cloud/ios-sdk/commit/017cca25748ddaa28f70c915105d1de57c3a6d58) to the `develop` branch, but unfortunately we have code in `develop` that is not yet ready for `master`. So my commit is just waiting there, doing nobody any good.

The legal questions make me hesitant to merge your `Cartfile` updates until we learn more--even though they are much needed and long overdue. Can you remove the changes to `Cartfile` and `Cartfile.resolved` so that the only changes are to `TextToSpeech.swift`?

Thanks @teddynewell! Really appreciate your work. :)

**Comment by teddynewell** [comment]
@glennrfisher reversed the changes to `Cartfile` and `Cartfile.resolved` so this PR only changes `TextToSpeech.swift`.

**Comment by glennrfisher** [comment]
Thanks, @teddynewell! Much appreciated.

**Comment by glennrfisher** [comment]
Forgot to push a new release yesterday. I tagged your fix and labeled it v0.1.2. It should now be accessible via Carthage.

**Comment by teddynewell** [comment]
Thank you @glennrfisher ! And good to hear about upcoming `SpeechToText` improvements – we are evaluating that service as well.

**Pull request merged**
