### PR TITLE
Add documentation for Visual Recognition

### PR DESCRIPTION
**Pull request by thomaspaulmann**
### Summary

The documentation of the Visual Recognition was a copy-paster-version of the Tone Analyzer Service and didn't make sense. I've added some simple text to explain the service and how to use f.e. Face Detection. All in all, nothing special ✌️

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
There are more small copy-paste-errors in the documentation. Should I correct them in this or a separated PR?

**Comment by thomaspaulmann** [comment]
There are some issues with Homebrew. Could you fix this please?

Here is the interesting part of the log:
```
Warning: Failed to delete /Library/Caches/Homebrew.
Please do so manually.
```

**Comment by vherrin** [comment]
@thomaspaulmann Thanks for the contributions to the repository.  Yes please create a PR for review.  One item to note, the actual documentation generated from jazzy lives in the gh-pages branch.

**Comment by glennrfisher** [comment]
Awesome! This is great feedback and an excellent fix. Thanks for the updates, @thomaspaulmann! I'll go ahead and merge this PR.

As you noted, if you come across other copy-paste errors in the documentation please feel free to open an issue or a PR. Either one is always very helpful for us, and we really appreciate the input.

**Comment by glennrfisher** [comment]
@thomaspaulmann: When does that error occur with Homebrew? I know there are some complications that were introduced with permissions on El Capitan. Maybe we can help track down the problem for you if you give us some more information?

**Comment by glennrfisher** [comment]
Here's a link to the documentation that @vherrin referred to: http://watson-developer-cloud.github.io/ios-sdk/

**Comment by thomaspaulmann** [comment]
@glennrfisher: The error occurred on Travis CI. I had no problems on my machine, I guess it's an issue of some homebrew updates. Other open source projects have the same error log. I will have a look for further PRs.

**Comment by thomaspaulmann** [comment]
@vherrin: Thanks for the link to the documentation. I noticed only some issues in the README on Github. Generally it's the first touchpoint for developers when they integrate a new SDK, so it would be perfect if everything works out of the box. I noticed also some errors in the QuickStart-Guide. I will contribute my changes in a separated PR. Thanks for having me :P

**Pull request merged**
